### ISSUE TITLE
Is it reasonable to only set hugepages?

### ISSUE THREAD

**Issue by cbandy** [openshift/cluster-node-tuning-operator#575]
I noticed that I could not create a PerformanceProfile dedicated to huge pages. Should it be possible to create one without specifying `cpu`?

```yaml
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: worker-hugepages
spec:
  hugepages:
    pages:
      - { size: 2M, count: 500 }
  nodeSelector:
    node-role.kubernetes.io/worker: ''
```

```console
$ oc apply --server-side -f worker-hugepages.yaml
The PerformanceProfile "worker-hugepages" is invalid: spec.cpu: Required value
```
